// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adeventservice.proto

// Protobuf Java Version: 3.25.2
package com.jsn.adevent.mapper.grpc;

public interface OffsetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Offset)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 offset = 1;</code>
   * @return The offset.
   */
  long getOffset();
}
