// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adeventservice.proto

// Protobuf Java Version: 3.25.2
package com.jsn.adevent.reducer.grpc;

public interface AdEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AdEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 adId = 1;</code>
   * @return The adId.
   */
  long getAdId();

  /**
   * <code>int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
