// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adeventservice.proto

// Protobuf Java Version: 3.25.2
package com.jsn.adevent.reducer.grpc;

public final class AdEventProto {
  private AdEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdEventMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AdEventMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AdEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Offset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Offset_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024adeventservice.proto\"&\n\nAdEventMap\022\030\n\006" +
      "events\030\001 \003(\0132\010.AdEvent\"?\n\007AdEvent\022\014\n\004adI" +
      "d\030\001 \001(\003\022\021\n\ttimestamp\030\002 \001(\003\022\023\n\013kafkaOffse" +
      "t\030\003 \001(\003\"\007\n\005Empty\"\030\n\006Offset\022\016\n\006offset\030\001 \001" +
      "(\00329\n\023AdClickEventService\022\"\n\tSendEvent\022\013" +
      ".AdEventMap\032\006.Empty\"\00020\n\rOffsetService\022\037" +
      "\n\nSendOffset\022\007.Offset\032\006.Empty\"\000B.\n\034com.j" +
      "sn.adevent.reducer.grpcB\014AdEventProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AdEventMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AdEventMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AdEventMap_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_AdEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AdEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AdEvent_descriptor,
        new java.lang.String[] { "AdId", "Timestamp", "KafkaOffset", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Offset_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Offset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Offset_descriptor,
        new java.lang.String[] { "Offset", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
