// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adeventservice.proto

// Protobuf Java Version: 3.25.2
package com.jsn.adevent.reducer.grpc;

public interface AdEventMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AdEventMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AdEvent events = 1;</code>
   */
  java.util.List<com.jsn.adevent.reducer.grpc.AdEvent> 
      getEventsList();
  /**
   * <code>repeated .AdEvent events = 1;</code>
   */
  com.jsn.adevent.reducer.grpc.AdEvent getEvents(int index);
  /**
   * <code>repeated .AdEvent events = 1;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .AdEvent events = 1;</code>
   */
  java.util.List<? extends com.jsn.adevent.reducer.grpc.AdEventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .AdEvent events = 1;</code>
   */
  com.jsn.adevent.reducer.grpc.AdEventOrBuilder getEventsOrBuilder(
      int index);
}
