// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adeventservice.proto

// Protobuf Java Version: 3.25.2
package com.jsn.adevent.reducer.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
